# Generated by Django 3.2.8 on 2021-12-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211212_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='content',
            field=models.ImageField(upload_to='avatar/%Y%m%d'),
        ),
    ]
