# Generated by Django 3.2.8 on 2021-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_avatar_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='content',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d/'),
        ),
    ]
