# Generated by Django 3.2.8 on 2021-12-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='isHiddden',
        ),
        migrations.AddField(
            model_name='comment',
            name='isShow',
            field=models.BooleanField(default=True),
        ),
    ]
