# Generated by Django 3.2.8 on 2022-01-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, verbose_name='房间名')),
                ('content', models.TextField(verbose_name='消息')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聊天记录表',
                'verbose_name_plural': '聊天记录表',
                'db_table': 'tb_chat',
                'ordering': ('created_time',),
            },
        ),
    ]
