# Generated by Django 3.2.8 on 2022-01-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_sendperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sendperson',
            new_name='sender',
        ),
    ]
