# Generated by Django 3.2.8 on 2021-11-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211128_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_time'], 'verbose_name': '分類', 'verbose_name_plural': '分類'},
        ),
        migrations.AddField(
            model_name='blog',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
