# Generated by Django 3.2.8 on 2022-02-20 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 11, 58, 101986, tzinfo=utc))),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='描述', null=True)),
                ('show', models.BooleanField(choices=[(False, '不展示'), (True, '展示')], default=False, help_text='是否展示')),
                ('thumbnail_url', models.URLField(blank=True, help_text='封面', null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('last_updated_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('category', models.ForeignKey(blank=True, help_text='友链分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='links.category')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
                'ordering': ['-created_time'],
            },
        ),
    ]
