# Generated by Django 3.2.8 on 2022-02-20 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 13, 21, 697794, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 14, 13, 21, 698281, tzinfo=utc), help_text='创建时间'),
        ),
    ]
