# Generated by Django 3.2.8 on 2022-02-20 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20220220_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='links',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
    ]
