# Generated by Django 3.2.8 on 2022-02-21 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20220220_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='links/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='添加时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='类别', max_length=50, unique=True),
        ),
    ]
