# Generated by Django 3.2.8 on 2022-02-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20220221_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='link_url',
            field=models.URLField(blank=True, help_text='链接地址', null=True),
        ),
    ]
